id: oi-wiki:math/du-2
name: Du
solution:
  cpp: /docs/math/code/du/du_2.cpp
target:
- '!test'
testcases:
  answer: /docs/math/examples/du/du_2.out
  input: /docs/math/examples/du/du_2.in
version: 1000
