language: python
cache:
  pip: true
  directories:
  - node_modules
python:
  - 3.6
before_install:
  - curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
  - source ~/.nvm/nvm.sh
  - nvm install 10.9
install:
  - pip install -r requirements.txt
  - npm install .
script:
  - chmod +x build.sh && ./build.sh
  - mkdocs build -v
  - node render_math.js
deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GH_TOKEN
  local-dir: site
  on:
    branch: master
after_deploy:
  - chmod +x BaiduPusher.sh && ./BaiduPusher.sh
