language: python
python:
  - 3.6
install:
  - pip install -r requirements.txt
script: chmod +x build.sh && ./build.sh
deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x deploy.sh && bash ./deploy.sh
  on:
    branch: master