# Project Information
site_name: OI Wiki
site_description: OI Wiki
site_author: OI Wiki Team
site_url: https://oi-wiki.cf
strict: true

# Repository
repo_name: '24OI/OI-wiki'
repo_url: 'https://github.com/24OI/OI-wiki'
edit_uri: 'blob/master/docs/'

# Copyright
copyright: 'Copyright &copy; 2016 - 2018 OI Wiki Team'

# Contents
nav:
  - 简介:
    - Getting Started: index.md
    - OI 赛制简介: introduction/mode.md
    - 学习资源: introduction/resources.md
    - 工具软件: introduction/softwares.md
  - 基础部分:
    - 基础部分简介: basic/index.md
    - 枚举: basic/enumerate.md
    - 模拟: basic/simulate.md
    - 分治: basic/divide-and-conquer.md
    - 贪心: basic/greedy.md
    - 排序: basic/sort.md
    - 表达式求值: basic/expression.md
    - 二分: basic/binary.md
    - 构造: basic/construction.md
  - 搜索:
    - 搜索部分简介: search/index.md
    - DFS: search/dfs.md
    - BFS: search/bfs.md
    - 双向广搜: search/dbfs.md
    - 启发式搜索: search/heuristic.md
    - Astar: search/astar.md
    - IDAstar: search/idastar.md
    - 迭代深搜: search/iterative.md
    - 回溯法: search/backtracking.md
    - Dancing Links: search/dlx.md
  - 动态规划:
    - 动态规划部分简介: dp/index.md
    - 记忆化搜索: dp/memo.md
    - 背包 DP: dp/backpack.md
    - 区间 DP: dp/interval.md
    - DAG 上的 dp: dp/dag.md
    - 树形 DP: dp/tree.md
    - 状压 DP: dp/state.md
    - 数位 DP: dp/number.md
    - 插头 DP: dp/plug.md
    - 优化及其它: dp/optimization.md
    - 其它动规方法: dp/misc.md
  - 字符串:
    - 字符串部分简介: string/index.md
    - 标准库: string/stl.md
    - 字符串匹配问题: string/match.md
    - 哈希大法: string/hash.md
    - 字典树（Trie）: string/trie.md
    - 回文自动机: string/pam.md
    - 回文树: string/palindrome-tree.md
    - 后缀数组（SA）: string/sa.md
    - AC 自动机: string/ac-automaton.md
    - 后缀自动机（SAM）: string/sam.md
    - 后缀树: string/suffix-tree.md
    - Manacher: string/manacher.md
    - 最小表示法: string/minimal-string.md
  - 数学:
    - 数学部分简介: math/index.md
    - 进制相关: math/base.md
    - 素数: math/prime.md
    - 最大公约数: math/gcd.md
    - 欧拉函数: math/euler.md
    - 筛法: math/sieve.md
    - 莫比乌斯反演: math/mobius.md
    - 费马小定理（欧拉定理）: math/fermat.md
    - 快速幂: math/quick-pow.md
    - 中国剩余定理: math/crt.md
    - 分段打表: math/dictionary.md
    - 矩阵: math/matrix.md
    - 位运算: math/bit.md
    - 乘法逆元: math/inverse.md
    - 阶 原根: math/primitive-root.md
    - BSGS: math/bsgs.md
    - 博弈论: math/game.md
    - 多项式黑科技: math/poly.md
    - 排列组合: math/combination.md
    - 卡特兰数: math/catalan.md
    - 斯特林数: math/stirling.md
    - 康托展开: math/cantor.md
    - 概率与期望: math/expectation.md
    - 置换群: math/permutation-group.md
    - 高斯消元: math/gauss.md
    - xor模线性方程组: math/linear-equations.md
    - 容斥原理: math/inclusion-exclusion-principle.md
    - 抽屉原理: math/drawer-principle.md
    - 数值与积分: math/integral.md
    - 快速傅里叶变换: math/fft.md
    - 快速数论变换: math/fnt.md
    - 线性规划: math/linear-programming.md
    - 杂项: math/misc.md
  - 数据结构:
    - 数据结构部分简介: data-structure/index.md
    - STL: data-structure/stl.md
    - pb_ds: data-structure/pb-ds.md
    - 基础数据结构:
      - 链表: data-structure/novice/linked-list.md
      - 哈希表: data-structure/novice/hash.md
      - 并查集: data-structure/novice/dsu.md
      - 堆: data-structure/novice/heap.md
      - 分块: data-structure/novice/square-root-decomposition.md
      - 单调栈: data-structure/novice/monotonous-stack.md
      - 单调队列: data-structure/novice/monotonous-queue.md
    - 中级数据结构:
      - 倍增法: data-structure/intermediate/sparse-table.md
      - 块状链表: data-structure/intermediate/block-list.md
      - 块状数组: data-structure/intermediate/block-array.md
      - 树状数组: data-structure/intermediate/bit.md
      - 线段树: data-structure/intermediate/segment.md
      - Treap: data-structure/intermediate/treap.md
      - SBT: data-structure/intermediate/sbt.md
      - Splay: data-structure/intermediate/splay.md
      - 替罪羊树: data-structure/intermediate/scapegoat.md
      - 虚树: data-structure/intermediate/virtual-tree.md
    - 高级数据结构:
      - 树套树:
        - 线段树套线段树: data-structure/advanced/seg-in-seg.md
        - 线段树套平衡树: data-structure/advanced/seg-in-balanced.md
        - 平衡树套线段树: data-structure/advanced/balanced-in-seg.md
      - AVL树: data-structure/advanced/avl.md
      - 划分树: data-structure/advanced/dividin.md
      - K-Dtree: data-structure/advanced/k-dtree.md
      - 可持久化线段树: data-structure/advanced/persistent-seg.md
      - 可持久化块状数组: data-structure/advanced/persistent-block-array.md
      - 可持久化平衡树: data-structure/advanced/persistent-balanced.md
      - 可持久化字典树: data-structure/advanced/persistent-trie.md
      - Link Cut Tree: data-structure/advanced/lct.md
      - Euler Tour Tree: data-structure/advanced/ett.md
      - 树分块: data-structure/advanced/tree-decompose.md
  - 图论:
    - 图论部分简介: graph/index.md
    - 图论基础: graph/basic.md
    - 树相关基础: graph/tree-basic.md
    - 遍历：BFS 和 DFS: graph/traverse.md
    - 最小生成树: graph/mst.md
    - 最近公共祖先: graph/lca.md
    - 树链剖分: graph/heavy-light-decomposition.md
    - 树分治: graph/tree-divide.md
    - 树的其他问题: graph/tree-misc.md
    - 拓扑排序: graph/topo.md
    - 动态树分治: graph/dynamic-tree-divide.md
    - 2-SAT: graph/2-sat.md
    - 欧拉图: graph/euler.md
    - 强连通分量: graph/scc.md
    - 双连通分量: graph/bcc.md
    - 割点割边: graph/bridge.md
    - 差分约束: graph/differential-constraints.md
    - 有向无环图: graph/dag.md
    - 二分图: graph/bi-graph.md
    - 最短路: graph/shortest-path.md
    - 最小环: graph/min-circle.md
    - k 短路: graph/kth-path.md
    - 欧拉图: graph/euler.md
    - 网络流: graph/flow.md
    - 拆点: graph/flow/node.md
    - 最大流: graph/flow/max-flow.md
    - 最小割: graph/flow/min-cut.md
    - 费用流: graph/flow/min-cost.md
    - 上下界网络流: graph/flow/bound.md
  - 计算几何:
    - 计算几何部分简介: geometry/index.md
    - 二维计算几何基础: geometry/2d.md
    - 三维计算几何基础: geometry/3d.md
    - pick定理: geometry/pick.md
    - 三角剖分: geometry/triangulation.md
    - 凸包: geometry/convex-hull.md
    - 扫描线: geometry/scanning.md
    - 旋转卡壳: geometry/rotating-calipers.md
    - 半平面交: geometry/half-plane-intersection.md
    - 其他黑科技: geometry/magic.md
  - 杂项:
    - 杂项简介: misc/index.md
    - 非传统题（提答大法）: misc/non-traditional.md
    - cdq分治: misc/cdq-divide.md
    - 莫队算法: misc/mo-algo.md
    - 爬山算法: misc/hill-climbing.md
    - 分数规划: misc/fractional-programming.md
    - 模拟退火: misc/simulated-annealing.md
    - 朱刘算法: misc/zhu-liu-algorithm.md
    - 随机增量法: misc/random-incremental.md
    - 随机化: misc/random.md
    - 离线处理: misc/offline.md
    - 各种距离: misc/distance.md
    - 字节顺序: misc/endianness.md
    - 复杂度: misc/complexity.md
    - 科学上网: misc/magic.md

# Theme
theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'white'
    accent: 'red'
  logo:
    icon: 'school'
  feature:
    tabs: true
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

# Customization
extra:
  search:
    language: 'jp'
  disqus: 'OI-Wiki'

extra_javascript:
  - '_static/js/extra.js'
  - 'https://cdn.bootcss.com/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML'

extra_css:
  - '_static/css/extra.css'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
