id: oi-wiki:ds/monotonous-queue-2
name: Monotonous Queue
solution:
  cpp: /docs/ds/code/monotonous-queue/monotonous-queue_2.cpp
target:
- '!test'
testcases:
  answer: /docs/ds/examples/monotonous-queue/monotonous-queue_2.out
  input: /docs/ds/examples/monotonous-queue/monotonous-queue_2.in
version: 1000
