id: oi-wiki:graph/2-sat-1
name: 2 Sat
solution:
  cpp: docs/graph/code/2-sat/2-sat_1.cpp
target:
- 'test'
testcases:
  answer: docs/graph/examples/2-sat/2-sat_1.out
  input: docs/graph/examples/2-sat/2-sat_1.in
version: 1000
