id: oi-wiki:ds/treap-1
name: Treap
solution:
  cpp: /docs/ds/code/treap/treap_1.cpp
target:
- '!test'
testcases:
  answer: /docs/ds/examples/treap/treap_1.out
  input: /docs/ds/examples/treap/treap_1.in
version: 1000
