id: oi-wiki:graph/steiner-tree-1
name: Steiner Tree
solution:
  cpp: docs/graph/code/steiner-tree/steiner-tree_1.cpp
target:
- 'test'
testcases:
  answer: docs/graph/examples/steiner-tree/steiner-tree_1.ans
  input: docs/graph/examples/steiner-tree/steiner-tree_1.in
version: 1000
