id: oi-wiki:ds/seg-1
name: SEG
solution:
  cpp: /docs/ds/code/seg/seg_1.cpp
target:
- '!test'
testcases:
  answer: /docs/ds/examples/seg/seg_1.out
  input: /docs/ds/examples/seg/seg_1.in
version: 1000
