id: oi-wiki:math/mobius-2
name: Mobius
solution:
  cpp: /docs/math/code/mobius/mobius_2.cpp
target:
- '!test'
testcases:
  answer: /docs/math/examples/mobius/mobius_2.out
  input: /docs/math/examples/mobius/mobius_2.in
version: 1000
