id: oi-wiki:math/mobius-1
name: Mobius
solution:
  cpp: /docs/math/code/mobius/mobius_1.cpp
target:
- '!test'
testcases:
  answer: /docs/math/examples/mobius/mobius_1.out
  input: /docs/math/examples/mobius/mobius_1.in
version: 1000
