id: oi-wiki:string/general-sam-1
name: General Sam
solution:
  cpp: docs/string/code/general-sam/general-sam_1.cpp
target:
- 'test'
testcases:
  answer: docs/string/examples/general-sam/general-sam_1.out
  input: docs/string/examples/general-sam/general-sam_1.in
version: 1000
