name: Build LaTeX document

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          latexmk_use_xelatex: true
          latexmk_shell_escape: true
          args: "-pdfxe -file-line-error -halt-on-error -interaction=nonstopmode -8bit -silent -logfilewarninglist- -pdfxelatex='xelatex --shell-escape %O %S -output-driver='xdvipdfmx -z0''"
          pre_compile: |
            apk add unzip wget curl coreutils nodejs npm imagemagick libwebp librsvg git py-pygments inkscape libxml2 > /dev/null
            (
            wget -q -O notosans.zip "https://noto-website-2.storage.googleapis.com/pkgs/NotoSans-hinted.zip"
            wget -q -O notoserif.zip "https://noto-website-2.storage.googleapis.com/pkgs/NotoSerif-hinted.zip"
            wget -q -O notoserifcjk.zip "https://noto-website-2.storage.googleapis.com/pkgs/NotoSerifCJKsc-hinted.zip"
            wget -q -O notosanscjk.zip "https://noto-website-2.storage.googleapis.com/pkgs/NotoSansCJKsc-hinted.zip"
            wget -q -O robotomono.zip "https://fonts.google.com/download?family=Roboto%20Mono"
            wget -q "http://mirrors.ctan.org/fonts/cm-unicode.zip"
            unzip -q notosans.zip -d notosans
            unzip -q notoserif.zip -d notoserif
            unzip -q notosanscjk.zip -d notosanscjk
            unzip -q notoserifcjk.zip -d notoserifcjk
            unzip -q robotomono.zip -d robotomono
            unzip -q ./cm-unicode.zip
            cp -r notosans notoserif notosanscjk notoserifcjk robotomono cm-unicode/fonts/otf/* /usr/share/fonts
            fc-cache
            git clone https://github.com/OI-wiki/OI-Wiki-export.git --depth=1
            ) > /dev/null
            cd ./OI-Wiki-export/remark-latex
            npm i > /dev/null
            cd ../..
            cd ./OI-Wiki-export/oi-wiki-export
            (
            npm i
            node index.js ../../
            ) > /dev/null
          root_file: |
            oi-wiki-export.tex
      - uses: actions/upload-artifact@v2
        with:
          name: OI-wiki.pdf
          path: ./OI-Wiki-export/oi-wiki-export/oi-wiki-export.pdf
