name: Check quotes

on: [ pull_request ]

jobs:
  check-quotes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - run: |
          if git diff -G[“”] HEAD^ -- '*.md' | grep ^+.*[“”]; then
            echo '::error::由于 `“……”` 未区分全半角，请使用 `「……」` 作为全角引号，`"..."` 作为半角引号。'
            exit 1
          fi
