name: Check quotes

on: [ pull_request_target ]

jobs:
  check-quotes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: refs/pull/${{ github.event.number }}/merge
          fetch-depth: 2
      - name: Check diff
        id: check-diff
        run: |
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "result<<$EOF" >> $GITHUB_OUTPUT
          git diff @^ -- '*.md' | grep -C 5 ^+.*[“”] >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT
      - name: If failed
        if: steps.check-diff.outputs.result
        uses: ntsd/auto-request-changes-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-body: |
            由于 `“……”` 未区分全半角，请使用 `「……」` 作为全角引号，`"..."` 作为半角引号。

            ```diff
            ${{ steps.check-diff.outputs.result }}
            ```

            这条消息是自动发出的。如果故意使用 `“……”`，请忽略此消息。
