# This is a basic workflow to help you get started with Actions

name: Gitee

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    if: github.repository_owner == 'OI-wiki'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Single repo mirror
        uses: Yikun/hub-mirror-action@master
        with:
          account_type: org
          src: github/OI-wiki
          dst: gitee/OI-wiki
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          white_list: "OI-wiki"
          force_update: true
          debug: true
